### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by a00s**
Created the schedule screens that can be saved on the mobile local storage. I temporary add a icon on the main screen.

### CODE REVIEW

**Comment by thejameslang** [comment]
@a00s looking good! quick question, did you generate this view through the ionic CLI?

**Comment by a00s** [comment]
Hello James
   Thank you -)
   Please let me know id I did on the wrong way.
From the console I run
ionic g page medhome

Then I changed the file in 
src/app/app.module.ts

and included 
import { MedhomePage } from '../pages/medhome/medhome';

declarations: [
...
MedhomePage
...
]

entryComponents: [
...
MedhomePage
...
],
------------------------
Btw there is a bug I'm going to try to fix today. If add a new alarm from the browser, when click save the list on the previous screen is automatically reload. But from my tablet it doesn't, I have to go back one screen more. I just have to find the right event, at this momment I'm using this
 ionViewWillEnter() {
    this.loadList();
  }

best regads

**Comment by a00s** [comment]
Changed to this one and start working. 
 ionViewDidEnter() {
    this.loadList();
  }
Now the issue is that the user can see the list flashing on the screen during loading time. In the future I will have to improve this.

**Comment by thejameslang** [comment]
@a00s no worries, that is correct. I'm trying to figure out why git is tracking changes in config.xml

did you change anything in that file?

**Comment by a00s** [comment]
About his file, I dont remeber changing manually, But I can see from here that if I add a plugin from ionic it will change the file.
Today was testing with the device and I can see that added this
` <allow-navigation href="http://192.168.1.69:8100"/>`
and probably for the next version will have the plugin for the alarm.

Would you like me to configure the git to ignore this this file when doing the push?

Another thing that happens in one main html when I changed and save, my editor changed the spaces on the beginning of the line.

**Comment by thejameslang** [comment]
@a00s which editor are you using?

**Comment by a00s** [comment]
Visual Studio Code on Linux. Maybe I can use the same one you are using so we have a more close set up.

**Comment by thejameslang** [comment]
hmm, that's what I'm using too. no worries, we can figure these quirks out later, I'll approve this pull request

**Comment by a00s** [comment]
thank you -)

**Pull request merged**
