### PR TITLE
Working alarm

### PR DESCRIPTION
**Pull request by a00s**
This version has a working alarm.
I add to the commit the folder plugin. The reason is that there is a bug in a cordova plugin, I open a bug issue on their github repository, once the bug is fixed we can remove the plugin folder from our repository.
https://github.com/katzer/cordova-plugin-local-notifications/issues/1229

On new version of Android there isn't a option to set repeated notifications with precise time. So every time an alarm is created, it will create notification for the next 30 days. Every time the application start it will clean the notifications and recreate then to be sure is accurate.

When the mobile is restarted, the notifications are removed by the SO, so this is one reason the notifications will be included again when the app starts.

On the home file it will call the local database to create the tables if they doesn't exist.

### CODE REVIEW

**Comment by a00s** [comment]
I need some more work on the top and bottom to fix the height. Depending to the screen size became too big.

**Comment by thejameslang** [comment]
@a00s thanks for the pull request. I do see quite a few extraneous folders. For some reason your plugins folder is not being ignored. I examined your .gitignore file and it seems it should be.

Also are you using bower?

**Comment by a00s** [comment]
Hello James. Sorry, That bower shouldn't be there, I'll find out how to remove and I'll be more careful next time.
-About the plugin folder, I intentionally added because of the schedule plugin that now is different from the original plugin. Do you have any suggestion, maybe I can add just the plugin folder related with the schedule, would reduce the size, or maybe we add a manual how to change so each developer would have to change on their local files.
-I just realize that every time I do I push on my repository, appear in this pull request, should that happen or did I configure something wrong on my git repository? I don't want to flood you with lots of pull requests each day.

**Comment by thejameslang** [comment]
no worries, i just wanted to keep our repository clean. and yes, your commits will show up with this pull request.

**Pull request merged**
